import { sql } from "drizzle-orm";
import {
  index,
  integer,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";
import { gateState, ticketStatus, weighKind, weighSource } from "./enums.js";
import { batches, varieties } from "./cotton.js";
import { counterparties, drivers, vehicles } from "./parties.js";
import { stations, users } from "./org.js";

/**
 * Борхати нақлиётию молӣ — the weigh ticket. One row per truckload.
 *
 * `grossG` / `tareG` / `netG` are a snapshot for querying. The **truth** is the
 * append-only `weighEvents` rows; `verifyTicketWeights()` reconciles the two and any
 * mismatch is an alarm, not something the application quietly repairs.
 */
export const weighTickets = pgTable(
  "weigh_tickets",
  {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),

    /** Idempotency key generated by the station before it goes to the server. */
    clientUuid: uuid("client_uuid").notNull(),

    /** Human serial printed on the paper, e.g. "T1-2026-000046". */
    serial: text("serial").notNull(),
    season: integer("season").notNull(),
    serialNumber: integer("serial_number").notNull(),

    status: ticketStatus("status").notNull().default("DRAFT"),
    gate: gateState("gate").notNull().default("ARRIVED"),

    // ---- who and what, straight off the paper form
    batchId: uuid("batch_id").references(() => batches.id),
    /** Борфиристонанда — the farm whose cotton this is, and who gets paid. */
    consignorId: uuid("consignor_id")
      .notNull()
      .references(() => counterparties.id),
    /** Фармоишгар (пулсупоранда) — payer, when different from the consignor. */
    payerId: uuid("payer_id").references(() => counterparties.id),
    driverId: uuid("driver_id").references(() => drivers.id),
    vehicleId: uuid("vehicle_id").references(() => vehicles.id),
    varietyId: uuid("variety_id").references(() => varieties.id),
    grade: integer("grade"),
    cottonClass: text("cotton_class"),
    /** Маҳалли бор кардан — loading place. */
    loadingPlace: text("loading_place"),
    /** Маҳалли супоридан — unloading place. */
    unloadingPlace: text("unloading_place"),
    routeNo: text("route_no"),

    // ---- weights, grams
    grossG: integer("gross_g"),
    tareG: integer("tare_g"),
    netG: integer("net_g"),

    // ---- lifecycle stamps
    stationId: uuid("station_id")
      .notNull()
      .references(() => stations.id),
    createdBy: uuid("created_by")
      .notNull()
      .references(() => users.id),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    /** True when this row first reached the server from an offline queue. */
    originatedOffline: integer("originated_offline").notNull().default(0),

    weighedAt: timestamp("weighed_at", { withTimezone: true }),
    analysedAt: timestamp("analysed_at", { withTimezone: true }),
    paidAt: timestamp("paid_at", { withTimezone: true }),
    departedAt: timestamp("departed_at", { withTimezone: true }),

    voidedAt: timestamp("voided_at", { withTimezone: true }),
    voidedBy: uuid("voided_by").references(() => users.id),
    voidReason: text("void_reason"),
  },
  (t) => [
    // A serial is printed on paper and must never repeat.
    uniqueIndex("weigh_tickets_serial_idx").on(t.serial),
    uniqueIndex("weigh_tickets_season_station_number_idx").on(
      t.season,
      t.stationId,
      t.serialNumber,
    ),
    // Replaying a queued offline creation can never make a second ticket.
    uniqueIndex("weigh_tickets_client_uuid_idx").on(t.clientUuid),
    index("weigh_tickets_status_idx").on(t.status),
    index("weigh_tickets_gate_idx").on(t.gate),
    index("weigh_tickets_batch_idx").on(t.batchId),
    index("weigh_tickets_consignor_idx").on(t.consignorId),
  ],
);

/**
 * Append-only record of every weighing. A wrong number is never edited: a new event is
 * appended with `supersedesId` set and a mandatory `reason`, and both stay visible.
 */
export const weighEvents = pgTable(
  "weigh_events",
  {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    clientUuid: uuid("client_uuid").notNull(),
    ticketId: uuid("ticket_id")
      .notNull()
      .references(() => weighTickets.id),
    kind: weighKind("kind").notNull(),
    weightG: integer("weight_g").notNull(),
    source: weighSource("source").notNull().default("manual"),

    /** Photo of the indicator display — the compensating control for manual entry. */
    photoRef: text("photo_ref"),
    /** Raw string from the weighbridge indicator, kept verbatim when source='indicator'. */
    indicatorRaw: text("indicator_raw"),

    capturedAt: timestamp("captured_at", { withTimezone: true }).notNull(),
    recordedAt: timestamp("recorded_at", { withTimezone: true }).notNull().defaultNow(),
    operatorId: uuid("operator_id")
      .notNull()
      .references(() => users.id),
    stationId: uuid("station_id")
      .notNull()
      .references(() => stations.id),
    deviceFingerprint: text("device_fingerprint"),
    originatedOffline: integer("originated_offline").notNull().default(0),

    /** Set when this event corrects an earlier one. Requires `reason`. */
    supersedesId: uuid("supersedes_id"),
    reason: text("reason"),
  },
  (t) => [
    uniqueIndex("weigh_events_client_uuid_idx").on(t.clientUuid),
    index("weigh_events_ticket_idx").on(t.ticketId),
    index("weigh_events_kind_idx").on(t.ticketId, t.kind),
  ],
);
