import { eq } from "drizzle-orm";
import { db } from "@/db/client";
import { auditLog, counterparties, drivers, vehicles } from "@/db/schema/index";
import { DomainError } from "@/domain/units";
import { normalisePlate } from "@/domain/plate";

/**
 * Records a тарозубон must be able to create with a truck sitting on the weighbridge.
 *
 * A truck turns up with a plate nobody has entered, or a farm delivers for the first
 * time. If the weigher cannot enter it there and then, he writes the load on paper and
 * "enters it later" — which is exactly the gap this system exists to close. So he can
 * create these records himself.
 *
 * The control is not prevention, it is visibility: every record carries who created it,
 * and the owner's dashboard lists the ones added at the weighbridge so they can be
 * checked against reality.
 *
 * The **id is generated by the station**, not the database, so a record created while
 * the station is offline can be referenced by the ticket queued behind it. The outbox
 * flushes in order, so the farm reaches the server before the Борхат that names it.
 */

export interface CreateCounterpartyInput {
  /** Station-generated UUID. Also the idempotency key. */
  id: string;
  kind: "farm" | "individual" | "company";
  name: string;
  tin?: string;
  defaultLocation?: string;
  brigadeCode?: string;
  phone?: string;
  createdBy: string;
}

export async function createCounterparty(input: CreateCounterpartyInput) {
  const name = input.name.trim();
  if (!name) throw new DomainError("Номи хоҷагӣ ҳатмист. / A name is required.");

  const tin = input.tin?.trim() || null;
  if (tin && !/^\d{9,12}$/.test(tin)) {
    throw new DomainError(
      "РЯМ/РМА бояд 9–12 рақам бошад. / A taxpayer ID must be 9–12 digits.",
    );
  }

  // Replay of a queued creation.
  const [existing] = await db
    .select()
    .from(counterparties)
    .where(eq(counterparties.id, input.id))
    .limit(1);
  if (existing) return { id: existing.id, name: existing.name, tin: existing.tin, created: false };

  const [row] = await db
    .insert(counterparties)
    .values({
      id: input.id,
      clientUuid: input.id,
      kind: input.kind,
      name,
      tin,
      defaultLocation: input.defaultLocation?.trim() || null,
      brigadeCode: input.brigadeCode?.trim() || null,
      phone: input.phone?.trim() || null,
      createdBy: input.createdBy,
    })
    .returning();
  if (!row) throw new Error("Could not create the counterparty.");

  await db.insert(auditLog).values({
    action: "counterparty.create",
    entityTable: "counterparties",
    entityId: row.id,
    payload: { name, tin, kind: input.kind },
    actorId: input.createdBy,
    occurredAt: new Date(),
  });

  return { id: row.id, name: row.name, tin: row.tin, created: true };
}

export interface CreateVehicleInput {
  id: string;
  plate: string;
  model?: string;
  transportOrg?: string;
  createdBy: string;
}

/**
 * A plate already on file is returned as-is rather than refused: the weigher typed a
 * truck that is already known, and the right answer is to select it, not to stop him.
 */
export async function createVehicle(input: CreateVehicleInput) {
  // Folds Cyrillic homoglyphs to Latin and collapses spacing, so "1234 АВ 01" typed on a
  // Cyrillic keyboard and "1234ab01" are the same truck. See src/domain/plate.ts.
  const { plate, standard } = normalisePlate(input.plate);

  const [byPlate] = await db.select().from(vehicles).where(eq(vehicles.plate, plate)).limit(1);
  if (byPlate) {
    return { id: byPlate.id, plate: byPlate.plate, model: byPlate.model, standard, created: false };
  }

  const [existing] = await db.select().from(vehicles).where(eq(vehicles.id, input.id)).limit(1);
  if (existing) {
    return {
      id: existing.id, plate: existing.plate, model: existing.model, standard, created: false,
    };
  }

  const [row] = await db
    .insert(vehicles)
    .values({
      id: input.id,
      clientUuid: input.id,
      plate,
      model: input.model?.trim() || null,
      transportOrg: input.transportOrg?.trim() || null,
      createdBy: input.createdBy,
    })
    .returning();
  if (!row) throw new Error("Could not create the vehicle.");

  await db.insert(auditLog).values({
    action: "vehicle.create",
    entityTable: "vehicles",
    entityId: row.id,
    // `standard: false` means the plate did not match a Tajik pattern — kept, but worth
    // the owner's eye on the review list.
    payload: { plate, model: row.model, standard },
    actorId: input.createdBy,
    occurredAt: new Date(),
  });

  return { id: row.id, plate: row.plate, model: row.model, standard, created: true };
}

export interface CreateDriverInput {
  id: string;
  fullName: string;
  phone?: string;
  createdBy: string;
}

export async function createDriver(input: CreateDriverInput) {
  const fullName = input.fullName.trim();
  if (!fullName) throw new DomainError("Ном ва насаб ҳатмист. / A name is required.");

  const [existing] = await db.select().from(drivers).where(eq(drivers.id, input.id)).limit(1);
  if (existing) return { id: existing.id, fullName: existing.fullName, created: false };

  const [row] = await db
    .insert(drivers)
    .values({
      id: input.id,
      clientUuid: input.id,
      fullName,
      phone: input.phone?.trim() || null,
      createdBy: input.createdBy,
    })
    .returning();
  if (!row) throw new Error("Could not create the driver.");

  await db.insert(auditLog).values({
    action: "driver.create",
    entityTable: "drivers",
    entityId: row.id,
    payload: { fullName },
    actorId: input.createdBy,
    occurredAt: new Date(),
  });

  return { id: row.id, fullName: row.fullName, created: true };
}
